name: Build Executables

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            artifact_name: windows-executable
            asset_name: 抽奖程序-windows.exe
          - os: macos-latest
            artifact_name: macos-executable  
            asset_name: 抽奖程序-macos
          - os: ubuntu-latest
            artifact_name: linux-executable
            asset_name: 抽奖程序-linux

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      shell: bash

    # 添加语法检查步骤
    - name: Check Python syntax
      run: |
        python -m py_compile batchRequest.py
        echo "✅ Python syntax check passed"

    # 可选：运行基本测试
    - name: Test script
      run: |
        python batchRequest.py --help || echo "Script executed"
      continue-on-error: true

    - name: Build executable
      run: |
        pyinstaller --onefile --console --name="${{ matrix.asset_name }}" batchRequest.py

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.artifact_name }}
        path: dist/
        retention-days: 30
